name: "List Pull Requests"
description: "list and put output pull requests"
branding:
  icon: "bell"
  color: "yellow"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ""
  label:
    description: "Label"
    required: true
    default: ""
outputs:
  result:
    description: "pull requests string"
runs:
  using: "node12"
  main: "dist/index.js"
